server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: booking-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/booking_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

grpc:
  client:
    wallet-service:
      address: ${GRPC_CLIENT_WALLET_SERVICE_ADDRESS:discovery:///wallet-service}
      enableKeepAlive: true
      negotiation-type: plaintext 

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true 

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://INVENTORY-SERVICE/ws}
report:
  service:
    url: ${REPORT_SERVICE_URL:http://REPORT-SERVICE}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always